CREATE TYPE gender AS ENUM (
    'Male',
    'Female',
    'Other'
);

CREATE TABLE adres (
    adres_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kraj TEXT NOT NULL,
    stan TEXT,
    kod_pocztowy TEXT NOT NULL,
    miasto TEXT NOT NULL,
    ulica TEXT NOT NULL,
    numer_domu TEXT NOT NULL,
    apartament TEXT
);
