CREATE TYPE gender AS ENUM (
    'Male',
    'Female',
    'Other'
);

CREATE TYPE notification_type AS ENUM (
    'SMS',
    'MAIL',
    'PUSH',
    'OTHER'
);

CREATE TYPE language_level AS ENUM (
    'A1',
    'A2',
    'B1',
    'B2',
    'C1',
    'C2'
);

CREATE TYPE project_status AS ENUM (
    'PENDING',
    'IN_PROGRESS',
    'SUSPENDED',
    'COMPLETED',
    'CANCELED'
);

CREATE TYPE recruitment_demand_status AS ENUM (
    'SUBMITTED',
    'UNDER_REVIEW',
    'APPROVED',
    'REJECTED',
    'IN_PROGRESS',
    'SUSPENDED',
    'COMPLETED'
);

CREATE TABLE address (
    address_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country TEXT NOT NULL,
    "state" TEXT,
    postal_code TEXT NOT NULL,
    city TEXT NOT NULL,
    street TEXT NOT NULL,
    "number" TEXT NOT NULL,
    apartment TEXT
);

CREATE TABLE "user" (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    password TEXT NOT NULL,
    gender GENDER NOT NULL,
    phone_number TEXT NOT NULL,
    birthday_date DATE NOT NULL,
    isActivated BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL ,
    modified_at TIMESTAMPTZ NOT NULL,
    address_id INTEGER NOT NULL REFERENCES address(address_id)
);

CREATE TABLE employee (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employed_at TIMESTAMPTZ NOT NULL,
    fired_at TIMESTAMPTZ NOT NULL,
    user_id INTEGER NOT NULL REFERENCES "user"(user_id)
);

CREATE TABLE hr_employee (
    hr_employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employee(employee_id)
);

CREATE TABLE project_manager (
    project_manager_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employee(employee_id)
);

CREATE TABLE administrator (
    administrator_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hr_employee_id INTEGER NOT NULL REFERENCES hr_employee(hr_employee_id),
    project_manager_id INTEGER NOT NULL REFERENCES project_manager(project_manager_id)
);

CREATE TABLE notification (
    notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    notification_type NOTIFICATION_TYPE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE notification_sending (
    pushed_at TIMESTAMPTZ,
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    notification_id INTEGER NOT NULL REFERENCES "notification"(notification_id),
    PRIMARY KEY (user_id, notification_id)
);

CREATE TABLE branch (
    branch_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_hq BOOLEAN NOT NULL,
    address_id INTEGER NOT NULL REFERENCES address(address_id)
);

CREATE TABLE employee_branch (
    started_at TIMESTAMPTZ,
    stopped_at TIMESTAMPTZ,
    employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
    branch_id INTEGER NOT NULL REFERENCES branch(branch_id),
    PRIMARY KEY (employee_id, branch_id)
);

CREATE TABLE department (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE employee_department (
    started_at TIMESTAMPTZ,
    stopped_at TIMESTAMPTZ,
    employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
    department_id INTEGER NOT NULL REFERENCES department(department_id),
    PRIMARY KEY (employee_id, department_id)
);

CREATE TABLE project (
    project_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "status" PROJECT_STATUS NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    project_manager_id INTEGER  NOT NULL REFERENCES project_manager(project_manager_id)
);

CREATE TABLE project_pm_permission (
    can_modify_roles BOOLEAN NOT NULL,
    can_create_interim_reports BOOLEAN NOT NULL,
    can_change_knowledge_of_project BOOLEAN NOT NULL,
    project_manager_id INTEGER NOT NULL REFERENCES project_manager(project_manager_id),
    project_id INTEGER NOT NULL REFERENCES project(project_id),
    PRIMARY KEY (project_manager_id, project_id)
);

CREATE TABLE project_knowledge (
    knowledge_level INTEGER NOT NULL CHECK (knowledge_level BETWEEN 1 AND 10),
    employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
    project_id INTEGER NOT NULL REFERENCES project(project_id),
    PRIMARY KEY (employee_id, project_id)
);

CREATE TABLE role (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    hourly_rate INTEGER NOT NULL,
    project_id INTEGER  NOT NULL REFERENCES project(project_id)
);

CREATE TABLE recruitment_demand (
    recruitment_demand_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "status" RECRUITMENT_DEMAND_STATUS NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    role_id INTEGER NOT NULL REFERENCES "role"(role_id),
    project_id INTEGER NOT NULL REFERENCES project(project_id)
);

CREATE TABLE interim_report (
    interim_report_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment TEXT NOT NULL,
    commitment INTEGER NOT NULL CHECK (commitment BETWEEN 1 AND 5),
    period_from DATE NOT NULL,
    period_to DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE language (
    language_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL
);

CREATE TABLE user_language_level (
    "level" LANGUAGE_LEVEL NOT NULL,
    employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
    language_id INTEGER NOT NULL REFERENCES "language"(language_id),
    hr_employee_id INTEGER NOT NULL REFERENCES hr_employee(hr_employee_id),
    PRIMARY KEY (employee_id, language_id)
);

CREATE TABLE skill (
    skill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE user_skill_level (
    "level" INTEGER NOT NULL CHECK (level BETWEEN 1 AND 5),
    employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
    skill_id INTEGER NOT NULL REFERENCES skill(skill_id),
    hr_employee_id INTEGER NOT NULL REFERENCES hr_employee(hr_employee_id),
    PRIMARY KEY (employee_id, skill_id)
);

CREATE TABLE role_skill_requirement (
    min_level INTEGER NOT NULL,
    role_id INTEGER NOT NULL REFERENCES "role"(role_id),
    skill_id INTEGER NOT NULL REFERENCES skill(skill_id),
    PRIMARY KEY (role_id, skill_id)
);

CREATE TABLE certificate (
    certificate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    institution TEXT
);

CREATE TABLE user_certificate_ownership (
    issued_at DATE NOT NULL,
    expire_at DATE,
    employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
    certificate_id INTEGER NOT NULL REFERENCES "certificate"(certificate_id),
    hr_employee_id INTEGER NOT NULL REFERENCES hr_employee(hr_employee_id),
    PRIMARY KEY (employee_id, certificate_id)
);

CREATE TABLE role_certificate_requirement (
    role_id INTEGER NOT NULL REFERENCES "role"(role_id),
    certificate_id INTEGER NOT NULL REFERENCES certificate(certificate_id),
    PRIMARY KEY (role_id, certificate_id)
);

CREATE TABLE education_level (
    education_level_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL
);

CREATE TABLE field_of_study (
    field_of_study_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL
);

CREATE TABLE university (
    university_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    country TEXT NOT NULL,
    city TEXT NOT NULL
);

CREATE TABLE education (
    education_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gratuation_year INTEGER NOT NULL,
    gratuation_month INTEGER NOT NULL,
    user_id INTEGER  NOT NULL REFERENCES "user"(user_id),
    hr_employee_id INTEGER NOT NULL REFERENCES hr_employee(hr_employee_id),
    education_level_id INTEGER NOT NULL REFERENCES education_level(education_level_id),
    field_of_study_id INTEGER NOT NULL REFERENCES field_of_study(field_of_study_id),
    university_id INTEGER NOT NULL REFERENCES university(university_id)
);

CREATE TABLE role_education_requirement (
    role_education_requirement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_level_id INTEGER REFERENCES education_level(education_level_id),
    university_id INTEGER REFERENCES university(university_id),
    field_of_study_id INTEGER REFERENCES field_of_study(field_of_study_id)
);

CREATE TABLE system_configuration (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE belbin_question (
    belbin_question_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,           
    statements TEXT[] NOT NULL     
);

CREATE TABLE belbin_test (
    belbin_test_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performed_at TIMESTAMPTZ NOT NULL,
    
    shaper_score INTEGER NOT NULL,
    specialist_score INTEGER NOT NULL,   
    plant_score INTEGER NOT NULL,        
    monitor_evaluator_score INTEGER NOT NULL, 
    completer_finisher_score INTEGER NOT NULL, 
    resource_investigator_score INTEGER NOT NULL, 
    coordinator_score INTEGER NOT NULL,  
    team_worker_score INTEGER NOT NULL,  
    implementer_score INTEGER NOT NULL,   

    employee_id INTEGER NOT NULL REFERENCES employee(employee_id) ON DELETE CASCADE,
    UNIQUE(employee_id) 
);