CREATE TYPE gender AS ENUM (
    'Male',
    'Female',
    'Other'
);

CREATE TYPE notification AS ENUM (
    'SMS',
    'MAIL',
    'PUSH',
    'OTHER'
);

CREATE TABLE address (
    address_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country TEXT NOT NULL,
    "state" TEXT,
    postal_code TEXT NOT NULL,
    city TEXT NOT NULL,
    street TEXT NOT NULL,
    "number" TEXT NOT NULL,
    apartment TEXT
);

CREATE TABLE branch (
    branch_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_hq BOOL NOT NULL,
    address_id INTEGER NOT NULL REFERENCES address(address_id)
);

CREATE TABLE department (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address_id INTEGER NOT NULL,
);


